-------------------------------------------chcit.EAI_DELIVERY-II-------------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_DELIVERY;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_DELIVERY
(AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, EAI_BPARTNER_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, DATEDELIVERED STRING, DESCRIPTION STRING, DOCSTATUS STRING, DOCUMENTNO STRING, ISACTIVE STRING, PROCESSED STRING, UPDATED STRING, UPDATEDBY DOUBLE, EAI_DELIVERY_ID DOUBLE, ISEXPORTED STRING, EXPORTTIME STRING, SITEDELIVERYID STRING, AD_SERVER_ID DOUBLE, VERSIONSTAMP DOUBLE, BUNDLEPACKAGECOUNT DOUBLE, ODDPACKAGECOUNT DOUBLE, ORDER_SERVER_ID DOUBLE, SOURCE_SERVER_ID DOUBLE, EAI_BPARTNER_LOCATION_ID DOUBLE, M_WAREHOUSE_ID DOUBLE, EXPECTDATEARRIVED STRING, CUSTOMER_ORG_ID DOUBLE, BAGCOUNT DOUBLE, EAI_ORDER_ID DOUBLE, CONSUMERPHONE STRING, CONSUMERADDRESS STRING, CONSUMERNAME STRING, WAYBILLCODE STRING, CARRIERCOMPANY STRING)
COMMENT 'EAI_DELIVERY details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_DELIVERY.txt' OVERWRITE INTO TABLE chcit.EAI_DELIVERY;
-------------------------------------------chcit.EAI_DELIVERYLINE-II-------------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_DELIVERYLINE;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_DELIVERYLINE
(AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, UPDATED STRING, UPDATEDBY DOUBLE, ISACTIVE STRING, GUARANTEEDATE STRING, LOT STRING, QTY DOUBLE, UOM STRING, EAI_DELIVERYLINE_ID DOUBLE, EAI_DELIVERY_ID DOUBLE, EAI_PRODUCT_ID DOUBLE, INVOICENO STRING, INVOICETYPENO STRING, DESCRIPTION STRING, LINE DOUBLE, PRICE DOUBLE, LINEAMT DOUBLE, SITEDELIVERYLINEID STRING, SITEINVOICEID STRING, SITEINVOICELINEID STRING, PROCESSED STRING, VERSIONSTAMP DOUBLE, PACKAGENO STRING, PRODUCTIONDATE STRING, SITEORDERID STRING, SITEORDERLINEID STRING, EAI_ORDERLINE_ID DOUBLE, ISODDPACKAGE STRING, DELIVERYNO STRING, PACKAGESEQNO DOUBLE, ISPRINTED STRING, PRINTCOUNT DOUBLE, LASTPRINTTIME STRING, EAI_ORDER_ID DOUBLE, VENDOR_PRODUCT_ID DOUBLE, VENDOR_QTY DOUBLE, VENDOR_PRICE DOUBLE, VENDOR_UOM STRING, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, QTYRECEIVED DOUBLE, QTYREJECTED DOUBLE, L_BUNDLE_QTY DOUBLE, M_BUNDLE_QTY DOUBLE, VENDOR_QTYRECEIVED DOUBLE, VENDOR_QTYREJECTED DOUBLE, PRODUCTAREA STRING)
COMMENT 'EAI_DELIVERYLINE details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_DELIVERYLINE.txt' OVERWRITE INTO TABLE chcit.EAI_DELIVERYLINE;
-------------------------------------------chcit.C_Invoice-II-------------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_Invoice;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_Invoice
(AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, DATEINVOICED STRING, DESCRIPTION STRING, DOCSTATUS STRING, DOCUMENTNO STRING, ISACTIVE STRING, ISRETURNDOC STRING, PROCESSED STRING, UPDATED STRING, UPDATEDBY DOUBLE, C_INVOICE_ID DOUBLE, TOTALAMT DOUBLE, ISEXPORTED STRING, EXPORTTIME STRING, SITEINVOICEID STRING, AD_SERVER_ID DOUBLE, C_ORDER_ID DOUBLE, ISPAID STRING, REJECTREASON STRING, VERSIONSTAMP DOUBLE, M_WAREHOUSE_ID DOUBLE, ISADJUSTDOC STRING, C_ORDERLINE_ID DOUBLE, ISSOTRX STRING, SOURCE_SERVER_ID DOUBLE, C_BPARTNER_ID DOUBLE, AD_DEPARTMENT_ID DOUBLE, SALESREPNAME STRING, DATEACCT STRING, ISLEGACY STRING, ISINTERNAL STRING, CONFIRMOR_ID DOUBLE, DUEDATE STRING, RECEIVEDATE STRING, RECEIVER_ID DOUBLE, ISPLAININVOICE STRING, C_PAYMENTTERM_ID DOUBLE, ISSELFMADE STRING, PAYMENTRULE STRING, ISINTERNALRETURN STRING, INVOICEADJUSTTYPE STRING, COMMITTIME STRING, COMMITTER_ID DOUBLE, CONFIRMUSER_ID DOUBLE, CONFIRMTIME STRING, SALESREP_ID DOUBLE, CREATOR_ID DOUBLE, CREATETIME STRING, COMMITUSER_ID DOUBLE)
COMMENT 'C_Invoice details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_Invoice.txt' OVERWRITE INTO TABLE chcit.C_Invoice;
-------------------------------------------chcit.AD_SERVER-II-------------------------------------------------------------
DROP TABLE IF EXISTS chcit.AD_SERVER;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.AD_SERVER
(AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, AD_SERVER_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, DESCRIPTION STRING, HOSTADDRESS STRING, HOSTPORT DOUBLE, ISACTIVE STRING, PASSWORD STRING, PROTOCOL STRING, SERVERLICENSE STRING, SERVERPATH STRING, SERVERUSER STRING, UPDATED STRING, UPDATEDBY DOUBLE, NAME STRING, PUBLICKEY STRING, ISSELFSERVER STRING, VALUE STRING, PRODUCT_SERVER_ID DOUBLE, ISAUXDOC STRING, SERVERTYPE STRING, SEQNO DOUBLE, VERSION STRING, VERSIONSTAMP DOUBLE, ISSUMMARY STRING, PARENT_ID DOUBLE, UUID STRING, ISNEEDSYNC STRING, MAXORGCOUNT DOUBLE, MSGFORMAT STRING, STARTDATE STRING, ENDDATE STRING, NAMESPACE STRING, PARAM1 STRING, PARAM2 STRING, PARAM3 STRING, SITE_SERVER_ID DOUBLE)
COMMENT 'AD_SERVER details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/AD_SERVER.txt' OVERWRITE INTO TABLE chcit.AD_SERVER;
-------------------------------------------chcit.AD_Org-II-----------------------------------------------------------------
DROP TABLE IF EXISTS chcit.AD_Org;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.AD_Org
(AD_ORG_ID DOUBLE, AD_CLIENT_ID DOUBLE, ISACTIVE STRING, CREATED STRING, CREATEDBY DOUBLE, UPDATED STRING, UPDATEDBY DOUBLE, VALUE STRING, NAME STRING, DESCRIPTION STRING, ISSUMMARY STRING, EAI_ORGCODE STRING, PRINTNAME STRING, AD_SERVER_ID DOUBLE, SITEORGNO STRING, PRODUCT_SERVER_ID DOUBLE, UUID STRING, ISNEEDSYNC STRING, VERSIONSTAMP DOUBLE, ISONLINESALE STRING, ISONLINEPURCHASE STRING, BPARTNER_SERVER_ID DOUBLE)
COMMENT 'AD_Org details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/AD_Org.txt' OVERWRITE INTO TABLE chcit.AD_Org;
-------------------------------------------chcit.C_InvoiceLine-II---------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_InvoiceLine;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_InvoiceLine
(AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, UPDATED STRING, UPDATEDBY DOUBLE, ISACTIVE STRING, GUARANTEEDATE STRING, LOT STRING, QTY DOUBLE, UOM STRING, C_INVOICELINE_ID DOUBLE, C_INVOICE_ID DOUBLE, INVOICENO STRING, INVOICETYPENO STRING, DESCRIPTION STRING, LINE DOUBLE, PRICE DOUBLE, LINEAMT DOUBLE, SITEINVOICELINEID STRING, C_ORDERLINE_ID DOUBLE, ISPAID STRING, PROCESSED STRING, VERSIONSTAMP DOUBLE, SITEDOCUMENTNO STRING, SITEORDERLINEID STRING, SITEORDERID STRING, PRODUCTIONDATE STRING, M_PRODUCT_ID DOUBLE, NOTAXPRICE DOUBLE, NOTAXLINEAMT DOUBLE, TAXRATE DOUBLE, PRICECOST DOUBLE, ISDISCOUNT STRING, PRICEPO DOUBLE, ORDERSITEVALUE STRING, AMTPAID DOUBLE, VENDOR_ID DOUBLE, DUEDATE STRING, PRICEINTERNAL DOUBLE, C_CONTRACTLINE_ID DOUBLE, C_PAYMENTTERM_ID DOUBLE, PAYDATE STRING, QTYNOTE DOUBLE, PRICENOTE DOUBLE, SALESREP_ID DOUBLE, QTYREJECTED DOUBLE, REJECTREASON STRING, SOPRICERP DOUBLE, PRICEQUOTE DOUBLE, ISINTERNALDOC STRING)
COMMENT 'C_InvoiceLine details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_InvoiceLine.txt' OVERWRITE INTO TABLE chcit.C_InvoiceLine;
-------------------------------------------chcit.C_BPartner-II------------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_BPartner;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_BPartner
(C_BPARTNER_ID DOUBLE, AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, UPDATED STRING, UPDATEDBY DOUBLE, NAME STRING, VALUE STRING, DESCRIPTION STRING, ISACTIVE STRING, ISSTOP STRING, ISQASTOP STRING, VERSIONSTAMP DOUBLE, BPARTNERCODE STRING, ISCUSTOMER STRING, ISVENDOR STRING, AD_SERVER_ID DOUBLE, LICENSETYPE STRING, LICENSENO STRING, MASTER_SERVER_ID DOUBLE, EAI_BPARTNER_ID DOUBLE, AD_ORGBP_ID DOUBLE)
COMMENT 'C_BPartner details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_BPartner.txt' OVERWRITE INTO TABLE chcit.C_BPartner;
-------------------------------------------chcit.M_Product-II-------------------------------------------------------------
DROP TABLE IF EXISTS chcit.M_Product;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.M_Product
(M_PRODUCT_ID DOUBLE, AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, UPDATED STRING, UPDATEDBY DOUBLE, NAME STRING, VALUE STRING, MEDICINENAME STRING, PRODUCTNAME STRING, PRODUCTSPEC STRING, PRODUCTSTYLE STRING, PRODUCTAREA STRING, MANUFACTURER STRING, DESCRIPTION STRING, ISACTIVE STRING, ISSTOP STRING, ISQASTOP STRING, UOM STRING, PRODUCTCODE STRING, L_BUNDLE_QTY DOUBLE, M_BUNDLE_QTY DOUBLE, S_BUNDLE_QTY DOUBLE, STORAGECONDITION STRING, PRODUCTCONTROLLEVEL STRING, UOMPRECISION DOUBLE, PRICELIST DOUBLE, CERTIFICATENO STRING, AD_SERVER_ID DOUBLE, MASTER_SERVER_ID DOUBLE, EAI_PRODUCT_ID DOUBLE, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, ISDOUBLECONFIRM STRING, CONSERVETYPE STRING, SOURCE_SERVER_ID DOUBLE, VERSIONSTAMP DOUBLE)
COMMENT 'M_Product details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/M_Product.txt' OVERWRITE INTO TABLE chcit.M_Product;
-------------------------------------------chcit.EAI_BPARTNER-II----------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_BPARTNER;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_BPARTNER
(EAI_BPARTNER_ID DOUBLE, AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, UPDATED STRING, UPDATEDBY DOUBLE, NAME STRING, VALUE STRING, DESCRIPTION STRING, ISACTIVE STRING, ISQASTOP STRING, VERSIONSTAMP DOUBLE, BPARTNERCODE STRING, ISCUSTOMER STRING, ISVENDOR STRING, ADDRESS STRING, LICENSETYPE STRING, LICENSENO STRING, HASGSPCERT STRING, HASGMPCERT STRING, CREDITCONTROL STRING, POSITION STRING, AD_ORGBP_ID DOUBLE, CONTACT STRING, PHONE STRING, CUSTOMERLEVEL STRING, LEGALPERSON STRING, CORPFUND DOUBLE, CHARGEPERSON STRING, BUSINESSSCOPE STRING, CONTACTIDNO STRING, CONTACTPHONE STRING, CONTACT2 STRING, CONTACTIDNO2 STRING, CONTACTPHONE2 STRING, ISSTOP STRING, AD_SERVER_ID DOUBLE, FULLNAME STRING, BPARTNERUID STRING, ISMANUALORDER STRING, SOURCE_SERVER_ID DOUBLE, SCORE DOUBLE, RANK STRING, BPARTNERUSERCODE STRING, BPARTNERTYPE STRING, ISAUDIT STRING, AUDITUSER_ID DOUBLE, AUDITTIME STRING, ISNEEDSYNC STRING, EAI_BP_GROUP_ID DOUBLE, ISONLINESALE STRING, ORGCODE STRING, ISINTERNAL STRING, SMSRECEIVENO STRING, MASTER_BPARTNER_ID DOUBLE, MASTER_SERVER_ID DOUBLE, SHORTNAME STRING, SUPERVISIONCODE STRING, M_WAREHOUSE_ID DOUBLE, CREDITDAYS DOUBLE, CREDITLIMITTEMP DOUBLE, CREDITLIMITTEMPVALIDTO STRING, C_PAYMENTTERM_ID DOUBLE, PO_PAYMENTTERM_ID DOUBLE, C_PAYMENTLIMIT_ID DOUBLE, CREDITSTATUS STRING, CREDITLIMIT DOUBLE, CUSTOMERMODAL STRING, ISCXCUSTOMER STRING, ISFXCUSTOMER STRING, ISKPCUSTOMER STRING, ISTCCUSTOMER STRING, ISTGCUSTOMER STRING, AD_DEPARTMENT_ID DOUBLE, PURCHASER_ID DOUBLE, ISCERTJYFW STRING)
COMMENT 'EAI_BPARTNER details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_BPARTNER.txt' OVERWRITE INTO TABLE chcit.EAI_BPARTNER;
-------------------------------------------chcit.EAI_PRODUCT-II-----------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_PRODUCT;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_PRODUCT
(EAI_PRODUCT_ID DOUBLE, AD_CLIENT_ID DOUBLE, AD_ORG_ID DOUBLE, CREATED STRING, CREATEDBY DOUBLE, UPDATED STRING, UPDATEDBY DOUBLE, NAME STRING, VALUE STRING, MEDICINESPEC STRING, DESCRIPTION STRING, ISACTIVE STRING, ISQASTOP STRING, PRODUCTTYPE STRING, PRODUCTSTYLE STRING, MANUFACTURER STRING, GUARANTEEDAYS DOUBLE, GUARANTEEDAYSMIN DOUBLE, L_BUNDLE_QTY DOUBLE, UOM STRING, OTCTYPE STRING, ISFOREIGN STRING, CERTIFICATENO STRING, PRODUCTCODE STRING, PRODUCTUSERCODE STRING, PRODUCTSTATECODE STRING, VERSIONSTAMP DOUBLE, PRODUCTAREA STRING, STOPREASON STRING, PRICELIST DOUBLE, CATEGORYTYPE STRING, PRICEPO DOUBLE, PRODUCTNAME STRING, PACKAGEMATERIAL STRING, PACKAGEQTY DOUBLE, UPC STRING, UOMPRECISION DOUBLE, ISSTOP STRING, ISHIDE STRING, AD_SERVER_ID DOUBLE, PRODUCTCONTROLLEVEL STRING, PRICESALE DOUBLE, STORAGECONDITION STRING, BASEUOM STRING, M_BUNDLE_QTY DOUBLE, S_BUNDLE_QTY DOUBLE, VERSION DOUBLE, INVOICEPRINTRULE STRING, SOURCE_SERVER_ID DOUBLE, ENGLISHNAME STRING, PINYIN STRING, CHEMICALNAME STRING, SPECIFICATIONNO STRING, EAI_PRODUCT_CATEGORY_ID DOUBLE, PRODUCTSTATEID STRING, CERTIFICATENO_OLD STRING, PRODUCTSPEC STRING, ISONLINESALE STRING, EFFECTTYPE STRING, EFFECTSUBTYPE STRING, ISAUDIT STRING, ISINDOUBT STRING, AUDITUSER_ID DOUBLE, AUDITTIME STRING, ISNEEDSYNC STRING, MEDICINENAME STRING, ISDOUBLECONFIRM STRING, CONSERVETYPE STRING, TAXRATE DOUBLE, ISSUPERVISION STRING, ISHASDOCUMENT STRING, MASTER_PRODUCT_ID DOUBLE, MASTER_SERVER_ID DOUBLE, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, STORAGECLASS STRING, M_MANUFACTURER_ID DOUBLE, POTAXRATE DOUBLE, DOCUMENTNOTE STRING, PACKAGESPEC STRING, INSURANCETYPE STRING, ISBASICMEDICINE STRING, BUSINESSSCOPE STRING, ISOTC STRING, ISINSURANCE STRING, CERTIFICATEVALIDDATE STRING, ISCOLDCHAIN STRING, PRODUCTSTRUCTURE STRING)
COMMENT 'EAI_PRODUCT details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_PRODUCT.txt' OVERWRITE INTO TABLE chcit.EAI_PRODUCT;

查询 某个节点 每天 每个客商 某个销售商品的累积数量数量和累积金额
