-------------------------------------------chcit.EAI_DELIVERY--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_DELIVERY;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_DELIVERY
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, EAI_BPARTNER_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, DATEDELIVERED TIMESTAMP, DESCRIPTION STRING, DOCSTATUS STRING, DOCUMENTNO STRING, ISACTIVE STRING, PROCESSED STRING, UPDATED TIMESTAMP, UPDATEDBY BIGINT, EAI_DELIVERY_ID FLOAT, ISEXPORTED STRING, EXPORTTIME TIMESTAMP, SITEDELIVERYID STRING, AD_SERVER_ID BIGINT, VERSIONSTAMP BIGINT, BUNDLEPACKAGECOUNT DOUBLE, ODDPACKAGECOUNT DOUBLE, ORDER_SERVER_ID BIGINT, SOURCE_SERVER_ID BIGINT, EAI_BPARTNER_LOCATION_ID BIGINT, M_WAREHOUSE_ID BIGINT, EXPECTDATEARRIVED TIMESTAMP, CUSTOMER_ORG_ID BIGINT, BAGCOUNT DOUBLE, EAI_ORDER_ID FLOAT, CONSUMERPHONE STRING, CONSUMERADDRESS STRING, CONSUMERNAME STRING, WAYBILLCODE STRING, CARRIERCOMPANY STRING)
COMMENT 'EAI_DELIVERY details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_DELIVERY.txt' OVERWRITE INTO TABLE chcit.EAI_DELIVERY;
-------------------------------------------chcit.EAI_DELIVERYLINE--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_DELIVERYLINE;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_DELIVERYLINE
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, ISACTIVE STRING, GUARANTEEDATE TIMESTAMP, LOT STRING, QTY DOUBLE, UOM STRING, EAI_DELIVERYLINE_ID FLOAT, EAI_DELIVERY_ID FLOAT, EAI_PRODUCT_ID BIGINT, INVOICENO STRING, INVOICETYPENO STRING, DESCRIPTION STRING, LINE BIGINT, PRICE DOUBLE, LINEAMT DOUBLE, SITEDELIVERYLINEID STRING, SITEINVOICEID STRING, SITEINVOICELINEID STRING, PROCESSED STRING, VERSIONSTAMP BIGINT, PACKAGENO STRING, PRODUCTIONDATE TIMESTAMP, SITEORDERID STRING, SITEORDERLINEID STRING, EAI_ORDERLINE_ID FLOAT, ISODDPACKAGE STRING, DELIVERYNO STRING, PACKAGESEQNO BIGINT, ISPRINTED STRING, PRINTCOUNT BIGINT, LASTPRINTTIME TIMESTAMP, EAI_ORDER_ID FLOAT, VENDOR_PRODUCT_ID BIGINT, VENDOR_QTY DOUBLE, VENDOR_PRICE DOUBLE, VENDOR_UOM STRING, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, QTYRECEIVED DOUBLE, QTYREJECTED DOUBLE, L_BUNDLE_QTY DOUBLE, M_BUNDLE_QTY DOUBLE, VENDOR_QTYRECEIVED DOUBLE, VENDOR_QTYREJECTED DOUBLE, PRODUCTAREA STRING)
COMMENT 'EAI_DELIVERYLINE details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_DELIVERYLINE.txt' OVERWRITE INTO TABLE chcit.EAI_DELIVERYLINE;
-------------------------------------------chcit.C_Invoice--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_Invoice;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_Invoice
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, DATEINVOICED TIMESTAMP, DESCRIPTION STRING, DOCSTATUS STRING, DOCUMENTNO STRING, ISACTIVE STRING, ISRETURNDOC STRING, PROCESSED STRING, UPDATED TIMESTAMP, UPDATEDBY BIGINT, C_INVOICE_ID FLOAT, TOTALAMT DOUBLE, ISEXPORTED STRING, EXPORTTIME TIMESTAMP, SITEINVOICEID STRING, AD_SERVER_ID BIGINT, C_ORDER_ID FLOAT, ISPAID STRING, REJECTREASON STRING, VERSIONSTAMP BIGINT, M_WAREHOUSE_ID BIGINT, ISADJUSTDOC STRING, C_ORDERLINE_ID FLOAT, ISSOTRX STRING, SOURCE_SERVER_ID BIGINT, C_BPARTNER_ID BIGINT, AD_DEPARTMENT_ID BIGINT, SALESREPNAME STRING, DATEACCT TIMESTAMP, ISLEGACY STRING, ISINTERNAL STRING, CONFIRMOR_ID BIGINT, DUEDATE TIMESTAMP, RECEIVEDATE TIMESTAMP, RECEIVER_ID BIGINT, ISPLAININVOICE STRING, C_PAYMENTTERM_ID BIGINT, ISSELFMADE STRING, PAYMENTRULE STRING, ISINTERNALRETURN STRING, INVOICEADJUSTTYPE STRING, COMMITTIME TIMESTAMP, COMMITTER_ID BIGINT, CONFIRMUSER_ID BIGINT, CONFIRMTIME TIMESTAMP, SALESREP_ID BIGINT, CREATOR_ID BIGINT, CREATETIME TIMESTAMP, COMMITUSER_ID BIGINT)
COMMENT 'C_Invoice details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_Invoice.txt' OVERWRITE INTO TABLE chcit.C_Invoice;
-------------------------------------------chcit.AD_SERVER--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.AD_SERVER;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.AD_SERVER
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, AD_SERVER_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, DESCRIPTION STRING, HOSTADDRESS STRING, HOSTPORT BIGINT, ISACTIVE STRING, PASSWORD STRING, PROTOCOL STRING, SERVERLICENSE STRING, SERVERPATH STRING, SERVERUSER STRING, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, PUBLICKEY STRING, ISSELFSERVER STRING, VALUE STRING, PRODUCT_SERVER_ID BIGINT, ISAUXDOC STRING, SERVERTYPE STRING, SEQNO BIGINT, VERSION STRING, VERSIONSTAMP BIGINT, ISSUMMARY STRING, PARENT_ID BIGINT, UUID STRING, ISNEEDSYNC STRING, MAXORGCOUNT BIGINT, MSGFORMAT STRING, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, NAMESPACE STRING, PARAM1 STRING, PARAM2 STRING, PARAM3 STRING, SITE_SERVER_ID BIGINT)
COMMENT 'AD_SERVER details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/AD_SERVER.txt' OVERWRITE INTO TABLE chcit.AD_SERVER;
-------------------------------------------chcit.AD_Org-----------------------------------------------------------------
DROP TABLE IF EXISTS chcit.AD_Org;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.AD_Org
(AD_ORG_ID BIGINT, AD_CLIENT_ID BIGINT, ISACTIVE STRING, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, VALUE STRING, NAME STRING, DESCRIPTION STRING, ISSUMMARY STRING, EAI_ORGCODE STRING, PRINTNAME STRING, AD_SERVER_ID BIGINT, SITEORGNO STRING, PRODUCT_SERVER_ID BIGINT, UUID STRING, ISNEEDSYNC STRING, VERSIONSTAMP BIGINT, ISONLINESALE STRING, ISONLINEPURCHASE STRING, BPARTNER_SERVER_ID BIGINT)
COMMENT 'AD_Org details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/AD_Org.txt' OVERWRITE INTO TABLE chcit.AD_Org;
-------------------------------------------chcit.C_InvoiceLine----------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_InvoiceLine;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_InvoiceLine
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, ISACTIVE STRING, GUARANTEEDATE TIMESTAMP, LOT STRING, QTY DOUBLE, UOM STRING, C_INVOICELINE_ID FLOAT, C_INVOICE_ID FLOAT, INVOICENO STRING, INVOICETYPENO STRING, DESCRIPTION STRING, LINE BIGINT, PRICE DOUBLE, LINEAMT DOUBLE, SITEINVOICELINEID STRING, C_ORDERLINE_ID FLOAT, ISPAID STRING, PROCESSED STRING, VERSIONSTAMP BIGINT, SITEDOCUMENTNO STRING, SITEORDERLINEID STRING, SITEORDERID STRING, PRODUCTIONDATE TIMESTAMP, M_PRODUCT_ID BIGINT, NOTAXPRICE DOUBLE, NOTAXLINEAMT DOUBLE, TAXRATE DOUBLE, PRICECOST DOUBLE, ISDISCOUNT STRING, PRICEPO DOUBLE, ORDERSITEVALUE STRING, AMTPAID DOUBLE, VENDOR_ID BIGINT, DUEDATE TIMESTAMP, PRICEINTERNAL DOUBLE, C_CONTRACTLINE_ID FLOAT, C_PAYMENTTERM_ID BIGINT, PAYDATE TIMESTAMP, QTYNOTE DOUBLE, PRICENOTE DOUBLE, SALESREP_ID BIGINT, QTYREJECTED DOUBLE, REJECTREASON STRING, SOPRICERP DOUBLE, PRICEQUOTE DOUBLE, ISINTERNALDOC STRING)
COMMENT 'C_InvoiceLine details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_InvoiceLine.txt' OVERWRITE INTO TABLE chcit.C_InvoiceLine;
-------------------------------------------chcit.C_BPartner-------------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_BPartner;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_BPartner
(C_BPARTNER_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, DESCRIPTION STRING, ISACTIVE STRING, ISSTOP STRING, ISQASTOP STRING, VERSIONSTAMP BIGINT, BPARTNERCODE STRING, ISCUSTOMER STRING, ISVENDOR STRING, AD_SERVER_ID BIGINT, LICENSETYPE STRING, LICENSENO STRING, MASTER_SERVER_ID BIGINT, EAI_BPARTNER_ID BIGINT, AD_ORGBP_ID BIGINT)
COMMENT 'C_BPartner details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_BPartner.txt' OVERWRITE INTO TABLE chcit.C_BPartner;
-------------------------------------------chcit.M_Product--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.M_Product;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.M_Product
(M_PRODUCT_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, MEDICINENAME STRING, PRODUCTNAME STRING, PRODUCTSPEC STRING, PRODUCTSTYLE STRING, PRODUCTAREA STRING, MANUFACTURER STRING, DESCRIPTION STRING, ISACTIVE STRING, ISSTOP STRING, ISQASTOP STRING, UOM STRING, PRODUCTCODE STRING, L_BUNDLE_QTY DOUBLE, M_BUNDLE_QTY DOUBLE, S_BUNDLE_QTY DOUBLE, STORAGECONDITION STRING, PRODUCTCONTROLLEVEL STRING, UOMPRECISION BIGINT, PRICELIST DOUBLE, CERTIFICATENO STRING, AD_SERVER_ID BIGINT, MASTER_SERVER_ID BIGINT, EAI_PRODUCT_ID BIGINT, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, ISDOUBLECONFIRM STRING, CONSERVETYPE STRING, SOURCE_SERVER_ID BIGINT, VERSIONSTAMP BIGINT)
COMMENT 'M_Product details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/M_Product.txt' OVERWRITE INTO TABLE chcit.M_Product;
-------------------------------------------chcit.EAI_BPARTNER-----------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_BPARTNER;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_BPARTNER
(EAI_BPARTNER_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, DESCRIPTION STRING, ISACTIVE STRING, ISQASTOP STRING, VERSIONSTAMP BIGINT, BPARTNERCODE STRING, ISCUSTOMER STRING, ISVENDOR STRING, ADDRESS STRING, LICENSETYPE STRING, LICENSENO STRING, HASGSPCERT STRING, HASGMPCERT STRING, CREDITCONTROL STRING, POSITION STRING, AD_ORGBP_ID BIGINT, CONTACT STRING, PHONE STRING, CUSTOMERLEVEL STRING, LEGALPERSON STRING, CORPFUND DOUBLE, CHARGEPERSON STRING, BUSINESSSCOPE STRING, CONTACTIDNO STRING, CONTACTPHONE STRING, CONTACT2 STRING, CONTACTIDNO2 STRING, CONTACTPHONE2 STRING, ISSTOP STRING, AD_SERVER_ID BIGINT, FULLNAME STRING, BPARTNERUID STRING, ISMANUALORDER STRING, SOURCE_SERVER_ID BIGINT, SCORE DOUBLE, RANK STRING, BPARTNERUSERCODE STRING, BPARTNERTYPE STRING, ISAUDIT STRING, AUDITUSER_ID BIGINT, AUDITTIME TIMESTAMP, ISNEEDSYNC STRING, EAI_BP_GROUP_ID BIGINT, ISONLINESALE STRING, ORGCODE STRING, ISINTERNAL STRING, SMSRECEIVENO STRING, MASTER_BPARTNER_ID BIGINT, MASTER_SERVER_ID BIGINT, SHORTNAME STRING, SUPERVISIONCODE STRING, M_WAREHOUSE_ID BIGINT, CREDITDAYS BIGINT, CREDITLIMITTEMP DOUBLE, CREDITLIMITTEMPVALIDTO TIMESTAMP, C_PAYMENTTERM_ID BIGINT, PO_PAYMENTTERM_ID BIGINT, C_PAYMENTLIMIT_ID BIGINT, CREDITSTATUS STRING, CREDITLIMIT DOUBLE, CUSTOMERMODAL STRING, ISCXCUSTOMER STRING, ISFXCUSTOMER STRING, ISKPCUSTOMER STRING, ISTCCUSTOMER STRING, ISTGCUSTOMER STRING, AD_DEPARTMENT_ID BIGINT, PURCHASER_ID DOUBLE, ISCERTJYFW STRING)
COMMENT 'EAI_BPARTNER details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_BPARTNER.txt' OVERWRITE INTO TABLE chcit.EAI_BPARTNER;
-------------------------------------------chcit.EAI_PRODUCT------------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_PRODUCT;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_PRODUCT
(EAI_PRODUCT_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, MEDICINESPEC STRING, DESCRIPTION STRING, ISACTIVE STRING, ISQASTOP STRING, PRODUCTTYPE STRING, PRODUCTSTYLE STRING, MANUFACTURER STRING, GUARANTEEDAYS BIGINT, GUARANTEEDAYSMIN BIGINT, L_BUNDLE_QTY DOUBLE, UOM STRING, OTCTYPE STRING, ISFOREIGN STRING, CERTIFICATENO STRING, PRODUCTCODE STRING, PRODUCTUSERCODE STRING, PRODUCTSTATECODE STRING, VERSIONSTAMP BIGINT, PRODUCTAREA STRING, STOPREASON STRING, PRICELIST DOUBLE, CATEGORYTYPE STRING, PRICEPO DOUBLE, PRODUCTNAME STRING, PACKAGEMATERIAL STRING, PACKAGEQTY DOUBLE, UPC STRING, UOMPRECISION BIGINT, ISSTOP STRING, ISHIDE STRING, AD_SERVER_ID BIGINT, PRODUCTCONTROLLEVEL STRING, PRICESALE DOUBLE, STORAGECONDITION STRING, BASEUOM STRING, M_BUNDLE_QTY DOUBLE, S_BUNDLE_QTY DOUBLE, VERSION BIGINT, INVOICEPRINTRULE STRING, SOURCE_SERVER_ID BIGINT, ENGLISHNAME STRING, PINYIN STRING, CHEMICALNAME STRING, SPECIFICATIONNO STRING, EAI_PRODUCT_CATEGORY_ID BIGINT, PRODUCTSTATEID STRING, CERTIFICATENO_OLD STRING, PRODUCTSPEC STRING, ISONLINESALE STRING, EFFECTTYPE STRING, EFFECTSUBTYPE STRING, ISAUDIT STRING, ISINDOUBT STRING, AUDITUSER_ID BIGINT, AUDITTIME TIMESTAMP, ISNEEDSYNC STRING, MEDICINENAME STRING, ISDOUBLECONFIRM STRING, CONSERVETYPE STRING, TAXRATE DOUBLE, ISSUPERVISION STRING, ISHASDOCUMENT STRING, MASTER_PRODUCT_ID BIGINT, MASTER_SERVER_ID BIGINT, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, STORAGECLASS STRING, M_MANUFACTURER_ID BIGINT, POTAXRATE DOUBLE, DOCUMENTNOTE STRING, PACKAGESPEC STRING, INSURANCETYPE STRING, ISBASICMEDICINE STRING, BUSINESSSCOPE STRING, ISOTC STRING, ISINSURANCE STRING, CERTIFICATEVALIDDATE TIMESTAMP, ISCOLDCHAIN STRING, PRODUCTSTRUCTURE STRING)
COMMENT 'EAI_PRODUCT details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_PRODUCT.txt' OVERWRITE INTO TABLE chcit.EAI_PRODUCT;
