-- temp
CREATE TABLE employee_hbase(key string,age int,sex string)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping" = ":key,info:age,info:sex")
TBLPROPERTIES ("hbase.table.name"="employee");
-- xxx
DROP TABLE IF EXISTS xxx;
CREATE EXTERNAL TABLE xxx(key string,xxx)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping" = ":key,xxx")
TBLPROPERTIES ("hbase.table.name"="xxx");

-- AD_Org
DROP TABLE IF EXISTS AD_Org;
CREATE EXTERNAL TABLE AD_Org(key string, AD_ORG_ID string, AD_CLIENT_ID string, ISACTIVE string, CREATED string, CREATEDBY string, UPDATED string, UPDATEDBY string, VALUE string, NAME string, DESCRIPTION string, ISSUMMARY string, EAI_ORGCODE string, PRINTNAME string, AD_SERVER_ID string, SITEORGNO string, PRODUCT_SERVER_ID string, UUID string, ISNEEDSYNC string, VERSIONSTAMP string, ISONLINESALE string, ISONLINEPURCHASE string, BPARTNER_SERVER_ID string)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping" = ":key,AD:AD_ORG_ID,AD:AD_CLIENT_ID,SETTING:ISACTIVE,TIME:CREATED,USER:CREATEDBY,TIME:UPDATED,USER:UPDATEDBY,AD:VALUE,AD:NAME,AD:DESCRIPTION,SETTING:ISSUMMARY,AD:EAI_ORGCODE,AD:PRINTNAME,AD:AD_SERVER_ID,AD:SITEORGNO,AD:PRODUCT_SERVER_ID,AD:UUID,SETTING:ISNEEDSYNC,VERSION:VERSIONSTAMP,SETTING:ISONLINESALE,SETTING:ISONLINEPURCHASE,AD:BPARTNER_SERVER_ID")
TBLPROPERTIES ("hbase.table.name"="AD_Org");

-- C_Invoice
DROP TABLE IF EXISTS C_Invoice;
CREATE EXTERNAL TABLE C_Invoice(key string,AD_CLIENT_ID string,AD_ORG_ID string,CREATED string,CREATEDBY string,DATEINVOICED string,DESCRIPTION string,DOCSTATUS string,DOCUMENTNO string,ISACTIVE string,ISRETURNDOC string,PROCESSED string,UPDATED string,UPDATEDBY string,C_INVOICE_ID string,TOTALAMT string,ISEXPORTED string,EXPORTTIME string,SITEINVOICEID string,AD_SERVER_ID string,C_ORDER_ID string,ISPAID string,REJECTREASON string,VERSIONSTAMP string,M_WAREHOUSE_ID string,ISADJUSTDOC string,C_ORDERLINE_ID string,ISSOTRX string,SOURCE_SERVER_ID string,C_BPARTNER_ID string,AD_DEPARTMENT_ID string,SALESREPNAME string,DATEACCT string,ISLEGACY string,ISINTERNAL string,SALESREP_ID string,CREATOR_ID string,CREATETIME string,COMMITUSER_ID string,COMMITTIME string,COMMITTER_ID string,CONFIRMUSER_ID string,CONFIRMTIME string,CONFIRMOR_ID string,DUEDATE string,RECEIVEDATE string,RECEIVER_ID string,ISPLAININVOICE string,C_PAYMENTTERM_ID string,ISSELFMADE string,PAYMENTRULE string,ISINTERNALRETURN string,INVOICEADJUSTTYPE string)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping" = ":key,AD:AD_CLIENT_ID,AD:AD_ORG_ID,TIME:CREATED,USER:CREATEDBY,INVOICE:DATEINVOICED,INVOICE:DESCRIPTION,INVOICE:DOCSTATUS,INVOICE:DOCUMENTNO,SETTING:ISACTIVE,SETTING:ISRETURNDOC,INVOICE:PROCESSED,TIME:UPDATED,USER:UPDATEDBY,BPARTNER:C_INVOICE_ID,INVOICE:TOTALAMT,INVOICE:ISEXPORTED,TIME:EXPORTTIME,INVOICE:SITEINVOICEID,AD:AD_SERVER_ID,INVOICE:C_ORDER_ID,SETTING:ISPAID,INVOICE:REJECTREASON,INVOICE:VERSIONSTAMP,INVOICE:M_WAREHOUSE_ID,SETTING:ISADJUSTDOC,BPARTNER:C_ORDERLINE_ID,INVOICE:ISSOTRX,AD:SOURCE_SERVER_ID,BPARTNER:C_BPARTNER_ID,AD:AD_DEPARTMENT_ID,INVOICE:SALESREPNAME,TIME:DATEACCT,SETTING:ISLEGACY,SETTING:ISINTERNAL,INVOICE:SALESREP_ID,USER:CREATOR_ID,TIME:CREATETIME,COMMIT:COMMITUSER_ID,COMMIT:COMMITTIME,COMMIT:COMMITTER_ID,CONFIRM:CONFIRMUSER_ID,CONFIRM:CONFIRMTIME,CONFIRM:CONFIRMOR_ID,TIME:DUEDATE,TIME:RECEIVEDATE,INVOICE:RECEIVER_ID,INVOICE:ISPLAININVOICE,BPARTNER:C_PAYMENTTERM_ID,SETTING:ISSELFMADE,INVOICE:PAYMENTRULE,SETTING:ISINTERNALRETURN,SETTING:INVOICEADJUSTTYPE")
TBLPROPERTIES ("hbase.table.name"="C_Invoice");

-- C_InvoiceLine
DROP TABLE IF EXISTS C_InvoiceLine;
CREATE EXTERNAL TABLE C_InvoiceLine(key string,AD_CLIENT_ID string,AD_ORG_ID string,AMTPAID string,C_CONTRACTLINE_ID string,C_INVOICE_ID string,C_INVOICELINE_ID string,C_ORDERLINE_ID string,C_PAYMENTTERM_ID string,CREATED string,CREATEDBY string,DESCRIPTION string,DUEDATE string,GUARANTEEDATE string,INVOICENO string,INVOICETYPENO string,ISACTIVE string,ISDISCOUNT string,ISINTERNALDOC string,ISPAID string,LINE string,LINEAMT string,LOT string,M_PRODUCT_ID string,NOTAXLINEAMT string,NOTAXPRICE string,ORDERSITEVALUE string,PAYDATE string,PRICE string,PRICECOST string,PRICEINTERNAL string,PRICENOTE string,PRICEPO string,PRICEQUOTE string,PROCESSED string,PRODUCTIONDATE string,QTY string,QTYNOTE string,QTYREJECTED string,REJECTREASON string,SALESREP_ID string,SITEDOCUMENTNO string,SITEINVOICELINEID string,SITEORDERID string,SITEORDERLINEID string,SOPRICERP string,TAXRATE string,UOM string,UPDATED string,UPDATEDBY string,VENDOR_ID string,VERSIONSTAMP string)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping" = ":key,AD:AD_CLIENT_ID,AD:AD_ORG_ID,INVOICELINE:AMTPAID,PURCHASE:C_CONTRACTLINE_ID,PURCHASE:C_INVOICE_ID,PURCHASE:C_INVOICELINE_ID,PURCHASE:C_ORDERLINE_ID,PURCHASE:C_PAYMENTTERM_ID,MODIFY:CREATED,MODIFY:CREATEDBY,INVOICELINE:DESCRIPTION,INVOICELINE:DUEDATE,INVOICELINE:GUARANTEEDATE,INVOICE:INVOICENO,INVOICE:INVOICETYPENO,INVOICELINE:ISACTIVE,INVOICELINE:ISDISCOUNT,INVOICELINE:ISINTERNALDOC,INVOICELINE:ISPAID,INVOICELINE:LINE,INVOICELINE:LINEAMT,INVOICELINE:LOT,PRODUCT:M_PRODUCT_ID,INVOICELINE:NOTAXLINEAMT,INVOICELINE:NOTAXPRICE,INVOICELINE:ORDERSITEVALUE,INVOICELINE:PAYDATE,INVOICELINE:PRICE,INVOICELINE:PRICECOST,INVOICELINE:PRICEINTERNAL,INVOICELINE:PRICENOTE,INVOICELINE:PRICEPO,INVOICELINE:PRICEQUOTE,INVOICELINE:PROCESSED,PRODUCT:PRODUCTIONDATE,INVOICELINE:QTY,INVOICELINE:QTYNOTE,INVOICELINE:QTYREJECTED,INVOICELINE:REJECTREASON,INVOICELINE:SALESREP_ID,INVOICELINE:SITEDOCUMENTNO,INVOICELINE:SITEINVOICELINEID,INVOICELINE:SITEORDERID,INVOICELINE:SITEORDERLINEID,INVOICELINE:SOPRICERP,INVOICELINE:TAXRATE,INVOICELINE:UOM,MODIFY:UPDATED,MODIFY:UPDATEDBY,INVOICELINE:VENDOR_ID,VERSION:VERSIONSTAMP")
TBLPROPERTIES ("hbase.table.name"="C_InvoiceLine");

-- EAI_BPartner
DROP TABLE IF EXISTS EAI_BPartner;
CREATE EXTERNAL TABLE EAI_BPartner(key string,EAI_BPARTNER_ID string,AD_CLIENT_ID string,AD_ORG_ID string,CREATED string,CREATEDBY string,UPDATED string,UPDATEDBY string,NAME string,VALUE string,DESCRIPTION string,ISACTIVE string,ISQASTOP string,VERSIONSTAMP string,BPARTNERCODE string,ISCUSTOMER string,ISVENDOR string,ADDRESS string,LICENSETYPE string,LICENSENO string,HASGSPCERT string,HASGMPCERT string,CREDITCONTROL string,POSITION string,AD_ORGBP_ID string,CONTACT string,PHONE string,CUSTOMERLEVEL string,LEGALPERSON string,CORPFUND string,CHARGEPERSON string,BUSINESSSCOPE string,CONTACTIDNO string,CONTACTPHONE string,CONTACT2 string,CONTACTIDNO2 string,CONTACTPHONE2 string,ISSTOP string,AD_SERVER_ID string,FULLNAME string,BPARTNERUID string,ISMANUALORDER string,SOURCE_SERVER_ID string,SCORE string,RANK string,BPARTNERUSERCODE string,BPARTNERTYPE string,ISAUDIT string,AUDITUSER_ID string,AUDITTIME string,ISNEEDSYNC string,EAI_BP_GROUP_ID string,ISONLINESALE string,ORGCODE string,ISINTERNAL string,SMSRECEIVENO string,MASTER_BPARTNER_ID string,MASTER_SERVER_ID string,SHORTNAME string,SUPERVISIONCODE string,C_PAYMENTTERM_ID string,PO_PAYMENTTERM_ID string,C_PAYMENTLIMIT_ID string,CREDITSTATUS string,CREDITLIMIT string,CUSTOMERMODAL string,ISCXCUSTOMER string,ISFXCUSTOMER string,ISKPCUSTOMER string,ISTCCUSTOMER string,ISTGCUSTOMER string,AD_DEPARTMENT_ID string,M_WAREHOUSE_ID string,CREDITDAYS string,CREDITLIMITTEMP string,CREDITLIMITTEMPVALIDTO string,PURCHASER_ID string,ISCERTJYFW string)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping" = ":key,BPARTNER:EAI_BPARTNER_ID,AD:AD_CLIENT_ID,AD:AD_ORG_ID,TIME:CREATED,USER:CREATEDBY,TIME:UPDATED,USER:UPDATEDBY,BPARTNER:NAME,BPARTNER:VALUE,BPARTNER:DESCRIPTION,BPARTNER:ISACTIVE,BPARTNER:ISQASTOP,VERSION:VERSIONSTAMP,BPARTNER:BPARTNERCODE,BPARTNER:ISCUSTOMER,BPARTNER:ISVENDOR,BPARTNER:ADDRESS,BPARTNER:LICENSETYPE,BPARTNER:LICENSENO,BPARTNER:HASGSPCERT,BPARTNER:HASGMPCERT,BPARTNER:CREDITCONTROL,BPARTNER:POSITION,AD:AD_ORGBP_ID,BPARTNER:CONTACT,BPARTNER:PHONE,BPARTNER:CUSTOMERLEVEL,BPARTNER:LEGALPERSON,BPARTNER:CORPFUND,BPARTNER:CHARGEPERSON,BPARTNER:BUSINESSSCOPE,BPARTNER:CONTACTIDNO,BPARTNER:CONTACTPHONE,BPARTNER:CONTACT2,BPARTNER:CONTACTIDNO2,BPARTNER:CONTACTPHONE2,BPARTNER:ISSTOP,AD:AD_SERVER_ID,BPARTNER:FULLNAME,BPARTNER:BPARTNERUID,BPARTNER:ISMANUALORDER,BPARTNER:SOURCE_SERVER_ID,BPARTNER:SCORE,BPARTNER:RANK,BPARTNER:BPARTNERUSERCODE,BPARTNER:BPARTNERTYPE,BPARTNER:ISAUDIT,BPARTNER:AUDITUSER_ID,BPARTNER:AUDITTIME,BPARTNER:ISNEEDSYNC,BPARTNER:EAI_BP_GROUP_ID,BPARTNER:ISONLINESALE,BPARTNER:ORGCODE,BPARTNER:ISINTERNAL,BPARTNER:SMSRECEIVENO,BPARTNER:MASTER_BPARTNER_ID,BPARTNER:MASTER_SERVER_ID,BPARTNER:SHORTNAME,BPARTNER:SUPERVISIONCODE,BPARTNER:C_PAYMENTTERM_ID,BPARTNER:PO_PAYMENTTERM_ID,BPARTNER:C_PAYMENTLIMIT_ID,BPARTNER:CREDITSTATUS,BPARTNER:CREDITLIMIT,BPARTNER:CUSTOMERMODAL,BPARTNER:ISCXCUSTOMER,BPARTNER:ISFXCUSTOMER,BPARTNER:ISKPCUSTOMER,BPARTNER:ISTCCUSTOMER,BPARTNER:ISTGCUSTOMER,AD:AD_DEPARTMENT_ID,BPARTNER:M_WAREHOUSE_ID,BPARTNER:CREDITDAYS,BPARTNER:CREDITLIMITTEMP,BPARTNER:CREDITLIMITTEMPVALIDTO,BPARTNER:PURCHASER_ID,BPARTNER:ISCERTJYFW")
TBLPROPERTIES ("hbase.table.name"="EAI_BPartner");

-- EAI_Product
DROP TABLE IF EXISTS EAI_Product;
CREATE EXTERNAL TABLE EAI_Product(key string,EAI_PRODUCT_ID string,AD_CLIENT_ID string,AD_ORG_ID string,CREATED string,CREATEDBY string,UPDATED string,UPDATEDBY string,NAME string,VALUE string,MEDICINESPEC string,DESCRIPTION string,ISACTIVE string,ISQASTOP string,PRODUCTTYPE string,PRODUCTSTYLE string,MANUFACTURER string,GUARANTEEDAYS string,GUARANTEEDAYSMIN string,L_BUNDLE_QTY string,UOM string,OTCTYPE string,ISFOREIGN string,CERTIFICATENO string,PRODUCTCODE string,PRODUCTUSERCODE string,PRODUCTSTATECODE string,VERSIONSTAMP string,PRODUCTAREA string,STOPREASON string,PRICELIST string,CATEGORYTYPE string,PRICEPO string,PRODUCTNAME string,PACKAGEMATERIAL string,PACKAGEQTY string,UPC string,UOMPRECISION string,ISSTOP string,ISHIDE string,AD_SERVER_ID string,PRODUCTCONTROLLEVEL string,PRICESALE string,STORAGECONDITION string,BASEUOM string,M_BUNDLE_QTY string,S_BUNDLE_QTY string,VERSION string,INVOICEPRINTRULE string,SOURCE_SERVER_ID string,ENGLISHNAME string,PINYIN string,CHEMICALNAME string,SPECIFICATIONNO string,EAI_PRODUCT_CATEGORY_ID string,PRODUCTSTATEID string,CERTIFICATENO_OLD string,PRODUCTSPEC string,ISONLINESALE string,EFFECTTYPE string,EFFECTSUBTYPE string,ISAUDIT string,ISINDOUBT string,AUDITUSER_ID string,AUDITTIME string,ISNEEDSYNC string,MEDICINENAME string,ISDOUBLECONFIRM string,CONSERVETYPE string,ISSUPERVISION string,ISHASDOCUMENT string,MULTIPLYRATE string,DIVIDERATE string,MASTER_PRODUCT_ID string,MASTER_SERVER_ID string,TAXRATE string,STORAGECLASS string,POTAXRATE string,M_MANUFACTURER_ID string,DOCUMENTNOTE string,CERTIFICATEVALIDDATE string,ISBASICMEDICINE string,PRODUCTSTRUCTURE string,ISCOLDCHAIN string,BUSINESSSCOPE string,ISOTC string,ISINSURANCE string,INSURANCETYPE string,PACKAGESPEC string)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES("hbase.columns.mapping" = ":key,PRODUCT:EAI_PRODUCT_ID,AD:AD_CLIENT_ID,AD:AD_ORG_ID,TIME:CREATED,USER:CREATEDBY,TIME:UPDATED,USER:UPDATEDBY,PRODUCT:NAME,PRODUCT:VALUE,PRODUCT:MEDICINESPEC,PRODUCT:DESCRIPTION,PRODUCT:ISACTIVE,PRODUCT:ISQASTOP,PRODUCT:PRODUCTTYPE,PRODUCT:PRODUCTSTYLE,PRODUCT:MANUFACTURER,PRODUCT:GUARANTEEDAYS,PRODUCT:GUARANTEEDAYSMIN,PRODUCT:L_BUNDLE_QTY,PRODUCT:UOM,PRODUCT:OTCTYPE,PRODUCT:ISFOREIGN,PRODUCT:CERTIFICATENO,PRODUCT:PRODUCTCODE,PRODUCT:PRODUCTUSERCODE,PRODUCT:PRODUCTSTATECODE,VERSION:VERSIONSTAMP,PRODUCT:PRODUCTAREA,PRODUCT:STOPREASON,PRODUCT:PRICELIST,PRODUCT:CATEGORYTYPE,PRODUCT:PRICEPO,PRODUCT:PRODUCTNAME,PRODUCT:PACKAGEMATERIAL,PRODUCT:PACKAGEQTY,PRODUCT:UPC,PRODUCT:UOMPRECISION,PRODUCT:ISSTOP,PRODUCT:ISHIDE,PRODUCT:AD_SERVER_ID,PRODUCT:PRODUCTCONTROLLEVEL,PRODUCT:PRICESALE,PRODUCT:STORAGECONDITION,PRODUCT:BASEUOM,PRODUCT:M_BUNDLE_QTY,PRODUCT:S_BUNDLE_QTY,PRODUCT:VERSION,PRODUCT:INVOICEPRINTRULE,PRODUCT:SOURCE_SERVER_ID,PRODUCT:ENGLISHNAME,PRODUCT:PINYIN,PRODUCT:CHEMICALNAME,PRODUCT:SPECIFICATIONNO,PRODUCT:EAI_PRODUCT_CATEGORY_ID,PRODUCT:PRODUCTSTATEID,PRODUCT:CERTIFICATENO_OLD,PRODUCT:PRODUCTSPEC,PRODUCT:ISONLINESALE,PRODUCT:EFFECTTYPE,PRODUCT:EFFECTSUBTYPE,PRODUCT:ISAUDIT,PRODUCT:ISINDOUBT,PRODUCT:AUDITUSER_ID,PRODUCT:AUDITTIME,PRODUCT:ISNEEDSYNC,PRODUCT:MEDICINENAME,PRODUCT:ISDOUBLECONFIRM,PRODUCT:CONSERVETYPE,PRODUCT:ISSUPERVISION,PRODUCT:ISHASDOCUMENT,PRODUCT:MULTIPLYRATE,PRODUCT:DIVIDERATE,PRODUCT:MASTER_PRODUCT_ID,PRODUCT:MASTER_SERVER_ID,PRODUCT:TAXRATE,PRODUCT:STORAGECLASS,PRODUCT:POTAXRATE,PRODUCT:M_MANUFACTURER_ID,PRODUCT:DOCUMENTNOTE,PRODUCT:CERTIFICATEVALIDDATE,PRODUCT:ISBASICMEDICINE,PRODUCT:PRODUCTSTRUCTURE,PRODUCT:ISCOLDCHAIN,PRODUCT:BUSINESSSCOPE,PRODUCT:ISOTC,PRODUCT:ISINSURANCE,PRODUCT:INSURANCETYPE,PRODUCT:PACKAGESPEC")
TBLPROPERTIES ("hbase.table.name"="EAI_Product");


select C_Invoice.AD_Org_ID,C_BPartner.name,C_Invoice.DateInvoiced,M_PRODUCT.NAME,SUM(C_InvoiceLine.Qty) QtY,SUM(C_InvoiceLine.LineAmt) Amt
  from C_Invoice
  LEFT JOIN C_InvoiceLine on  C_InvoiceLine.C_Invoice_ID=C_Invoice.C_Invoice_ID
  LEFT JOIN C_BPartner on C_Invoice.C_BPartner_ID=C_BPartner.C_BPartner_ID
  LEFT JOIN M_PRODUCT on C_InvoiceLine.M_PRODUCT_ID=M_PRODUCT.M_Product_ID
  where C_Invoice.AD_Org_ID='1000401'
  GROUP BY C_Invoice.AD_Org_ID,C_Invoice.DateInvoiced,C_BPartner.name,M_PRODUCT.NAME order by C_Invoice.DateInvoiced;

select AD_ORG.AD_Org_ID,M_PRODUCT.NAME,C_INVOICE.DateInvoiced
    from C_InvoiceLine
    JOIN C_Invoice on  C_InvoiceLine.C_Invoice_ID=C_Invoice.C_Invoice_ID
    LEFT JOIN M_PRODUCT on C_InvoiceLine.M_PRODUCT_ID=M_PRODUCT.M_Product_ID
    JOIN AD_ORG on C_InvoiceLine.AD_Org_ID=AD_ORG.AD_Org_ID
    GROUP BY AD_ORG.AD_Org_ID,M_PRODUCT.NAME,C_Invoice.DateInvoiced
-- 数据查询表
select AD_ORG.AD_Org_ID,M_PRODUCT.NAME,C_INVOICE.DateInvoiced,C_BPartner.C_BPartner_ID,SUM(C_InvoiceLine.Qty) QtY,SUM(C_InvoiceLine.LineAmt) Amt
  from C_InvoiceLine
  JOIN C_Invoice on  C_InvoiceLine.C_Invoice_ID=C_Invoice.C_Invoice_ID
  LEFT JOIN M_PRODUCT on C_InvoiceLine.M_PRODUCT_ID=M_PRODUCT.M_Product_ID
  JOIN AD_ORG on C_InvoiceLine.AD_Org_ID=AD_ORG.AD_Org_ID
  JOIN C_BPartner on C_Invoice.C_BPartner_ID=C_BPartner.C_BPartner_ID
  where AD_ORG.AD_Org_ID='1000401'
  GROUP BY AD_ORG.AD_Org_ID,M_PRODUCT.NAME,C_Invoice.DateInvoiced,C_BPartner.C_BPartner_ID order by C_Invoice.DateInvoiced


--hive
CREATE TABLE IF NOT EXISTS EAI_DELIVERYLINE ( AD_CLIENT_ID String, AD_ORG_ID String, CREATED String, CREATEDBY String, UPDATED String, UPDATEDBY String, ISACTIVE String, GUARANTEEDATE String, LOT String, QTY String, UOM String, EAI_DELIVERYLINE_ID String, EAI_DELIVERY_ID String, EAI_PRODUCT_ID String, INVOICENO String, INVOICETYPENO String, DESCRIPTION String, LINE String, PRICE String, LINEAMT String, SITEDELIVERYLINEID String, SITEINVOICEID String, SITEINVOICELINEID String, PROCESSED String, VERSIONSTAMP String, PACKAGENO String, PRODUCTIONDATE String, SITEORDERID String, SITEORDERLINEID String, EAI_ORDERLINE_ID String, ISODDPACKAGE String, DELIVERYNO String, PACKAGESEQNO String, ISPRINTED String, PRINTCOUNT String, LASTPRINTTIME String, EAI_ORDER_ID String, VENDOR_PRODUCT_ID String, VENDOR_QTY String, VENDOR_PRICE String, VENDOR_UOM String, MULTIPLYRATE String, DIVIDERATE String, QTYRECEIVED String, QTYREJECTED String, L_BUNDLE_QTY String, M_BUNDLE_QTY String, VENDOR_QTYRECEIVED String, VENDOR_QTYREJECTED String, PRODUCTAREA String)
COMMENT 'EAI_DELIVERYLINE details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

LOAD DATA INPATH '/user/EAI_DELIVERYLINE.txt' OVERWRITE INTO TABLE EAI_DELIVERYLINE;

DROP TABLE IF EXISTS EAI_DELIVERYLINE;
CREATE TABLE IF NOT EXISTS chcit.EAI_DELIVERYLINE
( AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, ISACTIVE STRING, GUARANTEEDATE TIMESTAMP, LOT STRING, QTY DOUBLE, UOM STRING, EAI_DELIVERYLINE_ID FLOAT, EAI_DELIVERY_ID FLOAT, EAI_PRODUCT_ID BIGINT, INVOICENO STRING, INVOICETYPENO STRING, DESCRIPTION STRING, LINE BIGINT, PRICE DOUBLE, LINEAMT DOUBLE, SITEDELIVERYLINEID STRING, SITEINVOICEID STRING, SITEINVOICELINEID STRING, PROCESSED STRING, VERSIONSTAMP BIGINT, PACKAGENO STRING, PRODUCTIONDATE TIMESTAMP, SITEORDERID STRING, SITEORDERLINEID STRING, EAI_ORDERLINE_ID FLOAT, ISODDPACKAGE STRING, DELIVERYNO STRING, PACKAGESEQNO BIGINT, ISPRINTED STRING, PRINTCOUNT BIGINT, LASTPRINTTIME TIMESTAMP, EAI_ORDER_ID FLOAT, VENDOR_PRODUCT_ID BIGINT, VENDOR_QTY DOUBLE, VENDOR_PRICE DOUBLE, VENDOR_UOM STRING, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, QTYRECEIVED DOUBLE, QTYREJECTED DOUBLE, L_BUNDLE_QTY DOUBLE, M_BUNDLE_QTY DOUBLE, VENDOR_QTYRECEIVED DOUBLE, VENDOR_QTYREJECTED DOUBLE, PRODUCTAREA STRING)
  COMMENT 'EAI_DELIVERYLINE details'
  ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\;'
  LINES TERMINATED BY '\n'
  STORED AS TEXTFILE;
DROP TABLE IF EXISTS AD_SERVER;
CREATE TABLE IF NOT EXISTS AD_SERVER
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, AD_SERVER_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, DESCRIPTION STRING, HOSTADDRESS STRING, HOSTPORT BIGINT, ISACTIVE STRING, PASSWORD STRING, PROTOCOL STRING, SERVERLICENSE STRING, SERVERPATH STRING, SERVERUSER STRING, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, PUBLICKEY STRING, ISSELFSERVER STRING, VALUE STRING, PRODUCT_SERVER_ID BIGINT, ISAUXDOC STRING, SERVERTYPE STRING, SEQNO BIGINT, VERSION STRING, VERSIONSTAMP BIGINT, ISSUMMARY STRING, PARENT_ID BIGINT, UUID STRING, ISNEEDSYNC STRING, MAXORGCOUNT BIGINT, MSGFORMAT STRING, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, NAMESPACE STRING, PARAM1 STRING, PARAM2 STRING, PARAM3 STRING, SITE_SERVER_ID BIGINT)
  COMMENT 'AD_SERVER details'
  ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\;'
  LINES TERMINATED BY '\n'
  STORED AS TEXTFILE;

DROP TABLE IF EXISTS EAI_DELIVERY;
CREATE TABLE IF NOT EXISTS EAI_DELIVERY
  (AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, EAI_BPARTNER_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, DATEDELIVERED TIMESTAMP, DESCRIPTION STRING, DOCSTATUS STRING, DOCUMENTNO STRING, ISACTIVE STRING, PROCESSED STRING, UPDATED TIMESTAMP, UPDATEDBY BIGINT, EAI_DELIVERY_ID FLOAT, ISEXPORTED STRING, EXPORTTIME TIMESTAMP, SITEDELIVERYID STRING, AD_SERVER_ID BIGINT, VERSIONSTAMP BIGINT, BUNDLEPACKAGECOUNT DOUBLE, ODDPACKAGECOUNT DOUBLE, ORDER_SERVER_ID BIGINT, SOURCE_SERVER_ID BIGINT, EAI_BPARTNER_LOCATION_ID BIGINT, M_WAREHOUSE_ID BIGINT, EXPECTDATEARRIVED TIMESTAMP, CUSTOMER_ORG_ID BIGINT, BAGCOUNT DOUBLE, EAI_ORDER_ID FLOAT, CONSUMERPHONE STRING, CONSUMERADDRESS STRING, CONSUMERNAME STRING, WAYBILLCODE STRING, CARRIERCOMPANY STRING)
  COMMENT 'EAI_DELIVERY details'
  ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\;'
  LINES TERMINATED BY '\n'
  STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_DELIVERY.txt' OVERWRITE INTO TABLE EAI_DELIVERY;

-------------------------------------------chcit.C_Invoice--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_Invoice;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_Invoice
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, DATEINVOICED TIMESTAMP, DESCRIPTION STRING, DOCSTATUS STRING, DOCUMENTNO STRING, ISACTIVE STRING, ISRETURNDOC STRING, PROCESSED STRING, UPDATED TIMESTAMP, UPDATEDBY BIGINT, C_INVOICE_ID FLOAT, TOTALAMT DOUBLE, ISEXPORTED STRING, EXPORTTIME TIMESTAMP, SITEINVOICEID STRING, AD_SERVER_ID BIGINT, C_ORDER_ID FLOAT, ISPAID STRING, REJECTREASON STRING, VERSIONSTAMP BIGINT, M_WAREHOUSE_ID BIGINT, ISADJUSTDOC STRING, C_ORDERLINE_ID FLOAT, ISSOTRX STRING, SOURCE_SERVER_ID BIGINT, C_BPARTNER_ID BIGINT, AD_DEPARTMENT_ID BIGINT, SALESREPNAME STRING, DATEACCT TIMESTAMP, ISLEGACY STRING, ISINTERNAL STRING, CONFIRMOR_ID BIGINT, DUEDATE TIMESTAMP, RECEIVEDATE TIMESTAMP, RECEIVER_ID BIGINT, ISPLAININVOICE STRING, C_PAYMENTTERM_ID BIGINT, ISSELFMADE STRING, PAYMENTRULE STRING, ISINTERNALRETURN STRING, INVOICEADJUSTTYPE STRING, COMMITTIME TIMESTAMP, COMMITTER_ID BIGINT, CONFIRMUSER_ID BIGINT, CONFIRMTIME TIMESTAMP, SALESREP_ID BIGINT, CREATOR_ID BIGINT, CREATETIME TIMESTAMP, COMMITUSER_ID BIGINT)
COMMENT 'C_Invoice details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_Invoice.txt' OVERWRITE INTO TABLE chcit.C_Invoice;
-------------------------------------------chcit.AD_SERVER--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.AD_SERVER;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.AD_SERVER
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, AD_SERVER_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, DESCRIPTION STRING, HOSTADDRESS STRING, HOSTPORT BIGINT, ISACTIVE STRING, PASSWORD STRING, PROTOCOL STRING, SERVERLICENSE STRING, SERVERPATH STRING, SERVERUSER STRING, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, PUBLICKEY STRING, ISSELFSERVER STRING, VALUE STRING, PRODUCT_SERVER_ID BIGINT, ISAUXDOC STRING, SERVERTYPE STRING, SEQNO BIGINT, VERSION STRING, VERSIONSTAMP BIGINT, ISSUMMARY STRING, PARENT_ID BIGINT, UUID STRING, ISNEEDSYNC STRING, MAXORGCOUNT BIGINT, MSGFORMAT STRING, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, NAMESPACE STRING, PARAM1 STRING, PARAM2 STRING, PARAM3 STRING, SITE_SERVER_ID BIGINT)
COMMENT 'AD_SERVER details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/AD_SERVER.txt' OVERWRITE INTO TABLE chcit.AD_SERVER;
-------------------------------------------chcit.AD_Org-----------------------------------------------------------------
DROP TABLE IF EXISTS chcit.AD_Org;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.AD_Org
(AD_ORG_ID BIGINT, AD_CLIENT_ID BIGINT, ISACTIVE STRING, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, VALUE STRING, NAME STRING, DESCRIPTION STRING, ISSUMMARY STRING, EAI_ORGCODE STRING, PRINTNAME STRING, AD_SERVER_ID BIGINT, SITEORGNO STRING, PRODUCT_SERVER_ID BIGINT, UUID STRING, ISNEEDSYNC STRING, VERSIONSTAMP BIGINT, ISONLINESALE STRING, ISONLINEPURCHASE STRING, BPARTNER_SERVER_ID BIGINT)
COMMENT 'AD_Org details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/AD_Org.txt' OVERWRITE INTO TABLE chcit.AD_Org;
-------------------------------------------chcit.C_InvoiceLine----------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_InvoiceLine;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_InvoiceLine
(AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, ISACTIVE STRING, GUARANTEEDATE TIMESTAMP, LOT STRING, QTY DOUBLE, UOM STRING, C_INVOICELINE_ID FLOAT, C_INVOICE_ID FLOAT, INVOICENO STRING, INVOICETYPENO STRING, DESCRIPTION STRING, LINE BIGINT, PRICE DOUBLE, LINEAMT DOUBLE, SITEINVOICELINEID STRING, C_ORDERLINE_ID FLOAT, ISPAID STRING, PROCESSED STRING, VERSIONSTAMP BIGINT, SITEDOCUMENTNO STRING, SITEORDERLINEID STRING, SITEORDERID STRING, PRODUCTIONDATE TIMESTAMP, M_PRODUCT_ID BIGINT, NOTAXPRICE DOUBLE, NOTAXLINEAMT DOUBLE, TAXRATE DOUBLE, PRICECOST DOUBLE, ISDISCOUNT STRING, PRICEPO DOUBLE, ORDERSITEVALUE STRING, AMTPAID DOUBLE, VENDOR_ID BIGINT, DUEDATE TIMESTAMP, PRICEINTERNAL DOUBLE, C_CONTRACTLINE_ID FLOAT, C_PAYMENTTERM_ID BIGINT, PAYDATE TIMESTAMP, QTYNOTE DOUBLE, PRICENOTE DOUBLE, SALESREP_ID BIGINT, QTYREJECTED DOUBLE, REJECTREASON STRING, SOPRICERP DOUBLE, PRICEQUOTE DOUBLE, ISINTERNALDOC STRING)
COMMENT 'C_InvoiceLine details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_InvoiceLine.txt' OVERWRITE INTO TABLE chcit.C_InvoiceLine;
-------------------------------------------chcit.C_BPartner-------------------------------------------------------------
DROP TABLE IF EXISTS chcit.C_BPartner;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.C_BPartner
(C_BPARTNER_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, DESCRIPTION STRING, ISACTIVE STRING, ISSTOP STRING, ISQASTOP STRING, VERSIONSTAMP BIGINT, BPARTNERCODE STRING, ISCUSTOMER STRING, ISVENDOR STRING, AD_SERVER_ID BIGINT, LICENSETYPE STRING, LICENSENO STRING, MASTER_SERVER_ID BIGINT, EAI_BPARTNER_ID BIGINT, AD_ORGBP_ID BIGINT)
COMMENT 'C_BPartner details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/C_BPartner.txt' OVERWRITE INTO TABLE chcit.C_BPartner;
-------------------------------------------chcit.M_Product--------------------------------------------------------------
DROP TABLE IF EXISTS chcit.M_Product;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.M_Product
(M_PRODUCT_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, MEDICINENAME STRING, PRODUCTNAME STRING, PRODUCTSPEC STRING, PRODUCTSTYLE STRING, PRODUCTAREA STRING, MANUFACTURER STRING, DESCRIPTION STRING, ISACTIVE STRING, ISSTOP STRING, ISQASTOP STRING, UOM STRING, PRODUCTCODE STRING, L_BUNDLE_QTY DOUBLE, M_BUNDLE_QTY DOUBLE, S_BUNDLE_QTY DOUBLE, STORAGECONDITION STRING, PRODUCTCONTROLLEVEL STRING, UOMPRECISION BIGINT, PRICELIST DOUBLE, CERTIFICATENO STRING, AD_SERVER_ID BIGINT, MASTER_SERVER_ID BIGINT, EAI_PRODUCT_ID BIGINT, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, ISDOUBLECONFIRM STRING, CONSERVETYPE STRING, SOURCE_SERVER_ID BIGINT, VERSIONSTAMP BIGINT)
COMMENT 'M_Product details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/M_Product.txt' OVERWRITE INTO TABLE chcit.M_Product;
-------------------------------------------chcit.EAI_BPARTNER-----------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_BPARTNER;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_BPARTNER
(EAI_BPARTNER_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, DESCRIPTION STRING, ISACTIVE STRING, ISQASTOP STRING, VERSIONSTAMP BIGINT, BPARTNERCODE STRING, ISCUSTOMER STRING, ISVENDOR STRING, ADDRESS STRING, LICENSETYPE STRING, LICENSENO STRING, HASGSPCERT STRING, HASGMPCERT STRING, CREDITCONTROL STRING, POSITION STRING, AD_ORGBP_ID BIGINT, CONTACT STRING, PHONE STRING, CUSTOMERLEVEL STRING, LEGALPERSON STRING, CORPFUND DOUBLE, CHARGEPERSON STRING, BUSINESSSCOPE STRING, CONTACTIDNO STRING, CONTACTPHONE STRING, CONTACT2 STRING, CONTACTIDNO2 STRING, CONTACTPHONE2 STRING, ISSTOP STRING, AD_SERVER_ID BIGINT, FULLNAME STRING, BPARTNERUID STRING, ISMANUALORDER STRING, SOURCE_SERVER_ID BIGINT, SCORE DOUBLE, RANK STRING, BPARTNERUSERCODE STRING, BPARTNERTYPE STRING, ISAUDIT STRING, AUDITUSER_ID BIGINT, AUDITTIME TIMESTAMP, ISNEEDSYNC STRING, EAI_BP_GROUP_ID BIGINT, ISONLINESALE STRING, ORGCODE STRING, ISINTERNAL STRING, SMSRECEIVENO STRING, MASTER_BPARTNER_ID BIGINT, MASTER_SERVER_ID BIGINT, SHORTNAME STRING, SUPERVISIONCODE STRING, M_WAREHOUSE_ID BIGINT, CREDITDAYS BIGINT, CREDITLIMITTEMP DOUBLE, CREDITLIMITTEMPVALIDTO TIMESTAMP, C_PAYMENTTERM_ID BIGINT, PO_PAYMENTTERM_ID BIGINT, C_PAYMENTLIMIT_ID BIGINT, CREDITSTATUS STRING, CREDITLIMIT DOUBLE, CUSTOMERMODAL STRING, ISCXCUSTOMER STRING, ISFXCUSTOMER STRING, ISKPCUSTOMER STRING, ISTCCUSTOMER STRING, ISTGCUSTOMER STRING, AD_DEPARTMENT_ID BIGINT, PURCHASER_ID DOUBLE, ISCERTJYFW STRING)
COMMENT 'EAI_BPARTNER details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_BPARTNER.txt' OVERWRITE INTO TABLE chcit.EAI_BPARTNER;
-------------------------------------------chcit.EAI_PRODUCT------------------------------------------------------------
DROP TABLE IF EXISTS chcit.EAI_PRODUCT;
CREATE EXTERNAL TABLE IF NOT EXISTS chcit.EAI_PRODUCT
(EAI_PRODUCT_ID BIGINT, AD_CLIENT_ID BIGINT, AD_ORG_ID BIGINT, CREATED TIMESTAMP, CREATEDBY BIGINT, UPDATED TIMESTAMP, UPDATEDBY BIGINT, NAME STRING, VALUE STRING, MEDICINESPEC STRING, DESCRIPTION STRING, ISACTIVE STRING, ISQASTOP STRING, PRODUCTTYPE STRING, PRODUCTSTYLE STRING, MANUFACTURER STRING, GUARANTEEDAYS BIGINT, GUARANTEEDAYSMIN BIGINT, L_BUNDLE_QTY DOUBLE, UOM STRING, OTCTYPE STRING, ISFOREIGN STRING, CERTIFICATENO STRING, PRODUCTCODE STRING, PRODUCTUSERCODE STRING, PRODUCTSTATECODE STRING, VERSIONSTAMP BIGINT, PRODUCTAREA STRING, STOPREASON STRING, PRICELIST DOUBLE, CATEGORYTYPE STRING, PRICEPO DOUBLE, PRODUCTNAME STRING, PACKAGEMATERIAL STRING, PACKAGEQTY DOUBLE, UPC STRING, UOMPRECISION BIGINT, ISSTOP STRING, ISHIDE STRING, AD_SERVER_ID BIGINT, PRODUCTCONTROLLEVEL STRING, PRICESALE DOUBLE, STORAGECONDITION STRING, BASEUOM STRING, M_BUNDLE_QTY DOUBLE, S_BUNDLE_QTY DOUBLE, VERSION BIGINT, INVOICEPRINTRULE STRING, SOURCE_SERVER_ID BIGINT, ENGLISHNAME STRING, PINYIN STRING, CHEMICALNAME STRING, SPECIFICATIONNO STRING, EAI_PRODUCT_CATEGORY_ID BIGINT, PRODUCTSTATEID STRING, CERTIFICATENO_OLD STRING, PRODUCTSPEC STRING, ISONLINESALE STRING, EFFECTTYPE STRING, EFFECTSUBTYPE STRING, ISAUDIT STRING, ISINDOUBT STRING, AUDITUSER_ID BIGINT, AUDITTIME TIMESTAMP, ISNEEDSYNC STRING, MEDICINENAME STRING, ISDOUBLECONFIRM STRING, CONSERVETYPE STRING, TAXRATE DOUBLE, ISSUPERVISION STRING, ISHASDOCUMENT STRING, MASTER_PRODUCT_ID BIGINT, MASTER_SERVER_ID BIGINT, MULTIPLYRATE DOUBLE, DIVIDERATE DOUBLE, STORAGECLASS STRING, M_MANUFACTURER_ID BIGINT, POTAXRATE DOUBLE, DOCUMENTNOTE STRING, PACKAGESPEC STRING, INSURANCETYPE STRING, ISBASICMEDICINE STRING, BUSINESSSCOPE STRING, ISOTC STRING, ISINSURANCE STRING, CERTIFICATEVALIDDATE TIMESTAMP, ISCOLDCHAIN STRING, PRODUCTSTRUCTURE STRING)
COMMENT 'EAI_PRODUCT details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
LOAD DATA INPATH '/user/data/EAI_PRODUCT.txt' OVERWRITE INTO TABLE chcit.EAI_PRODUCT;
