/user/data/EAI_DELIVERYLINE
/user/data/AD_SERVER
/user/data/AD_Org
/user/data/C_Invoice
/user/data/C_InvoiceLine
/user/data/C_BPartner
/user/data/M_Product
/user/data/EAI_BPARTNER
/user/data/EAI_PRODUCT
