let iCanHazVundle=1
let vundle_readme=expand('$HOME/vimfiles/bundle/Vundle.vim/README.md')
if !filereadable(vundle_readme)
    silent !mkdir -p vimfiles/bundle
    silent !git clone https://github.com/VundleVim/Vundle.vim.git vimfiles/bundle/Vundle.vim
    let iCanHazVundle=0
endif
"""""""" 插件管理Vundle""""""""
"关闭兼容模式
set nocompatible
filetype off
set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
call vundle#begin('$HOME/vimfiles/bundle/')
Plugin 'VundleVim/Vundle.vim'
" -------------------------------插件列表----------------------------------
Plugin 'alvan/vim-closetag'
Plugin 'vim-scripts/L9'
Plugin 'w0rp/ale'
Plugin 'scrooloose/nerdtree'
Plugin 'xuyuanp/nerdtree-git-plugin'
Plugin 'yggdroot/indentline'
Plugin 'airblade/vim-gitgutter'
Plugin 'mattn/emmet-vim'
Plugin 'leshill/vim-json'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-git'
Plugin 'gregsexton/gitv'
Plugin 'marijnh/tern_for_vim'
Plugin 'Shougo/neocomplete.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tomtom/tcomment_vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'maksimr/vim-jsbeautify'
Plugin 'beautify-web/js-beautify'
Plugin 'majutsushi/tagbar'
Plugin 'jiangmiao/auto-pairs'
Plugin 'Mark'
Plugin 'ap/vim-css-color'
Plugin 'othree/csscomplete.vim'
Plugin 'ai/autoprefixer'
Plugin 'vim-autoprefixer'
Plugin 'godlygeek/tabular'
Plugin 'tpope/vim-markdown'
Plugin 'sirver/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'easymotion/vim-easymotion'
Plugin 'dkprice/vim-easygrep'
Plugin 'pangloss/vim-javascript'
Plugin 'taglist.vim'
Plugin 'mbbill/undotree'
Plugin 'matze/vim-move'
Plugin 'vim-expand-region'
Plugin 'rking/ag.vim'
Plugin 'gregsexton/matchtag'
Plugin 'othree/html5.vim'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'wesq3/vim-windowswap'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'haya14busa/incsearch.vim'
Plugin 'haya14busa/incsearch-fuzzy.vim'
Plugin 'itspriddle/vim-stripper'
Plugin 'ryanoasis/vim-devicons'
Plugin 'Smart-Tabs'
if iCanHazVundle == 0
    :PluginInstall
endif
call vundle#end()
filetype plugin indent on

let mapleader=";"
let g:mapleader = ";"
cd D:\bluhuu\ZimNotes
" 引入插件的设置
" source $HOME/vimfiles/setting/ctrlp-funky.vim
source $HOME/vimfiles/setting/ctrlp.vim
source $HOME/vimfiles/setting/ale.vim
" source $HOME/vimfiles/setting/delimitMate.vim
"source $HOME/vimfiles/setting/gundo.vim
source $HOME/vimfiles/setting/molokai.vim
source $HOME/vimfiles/setting/neocomplcache.vim
source $HOME/vimfiles/setting/NerdTree.vim
source $HOME/vimfiles/setting/tern_for_vim.vim
source $HOME/vimfiles/setting/vim-jsbeautify.vim
" source $HOME/vimfiles/setting/phpqa.vim
" source $HOME/vimfiles/setting/tabular.vim
source $HOME/vimfiles/setting/tagbar.vim
source $HOME/vimfiles/setting/vim-airline.vim
source $HOME/vimfiles/setting/vim-easymotion.vim
source $HOME/vimfiles/setting/vim-expand-region.vim
source $HOME/vimfiles/setting/vim-multiple-cursors.vim
" source $HOME/vimfiles/setting/vim-quickrun.vim
" 自定义设置
source $HOME/vimfiles/setting/custome.vim
set runtimepath^=$HOME/vimfiles/bundle/ag.vim
" let vundle_readme=expand('$HOME/vimfiles/bundle/Vundle.vim/README.md')
